### ISSUE TITLE
Not imported windows.py

### ISSUE THREAD

**Issue by Semihal** [Avlyssna/gpu-info#1]
Hello. Trying to import windows.py but does that not hvatatet module file base.
```
>>> import gpuinfo.windows
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\gpuinfo\windows.py", line 6, in <module>
    import base
ModuleNotFoundError: No module named 'base'
```

**Comment by Avlyssna** [comment]
This issue was fixed in commit 9a1699aaf00e8086acafa491992e2425eb950ea2.
